// Inherit the parent event
event_inherited();
hp = 120;
state = "norm";
walk_sp = 1.3;
hsp = walk_sp;
run_sp = 3.1;
jumped = false;
jump_sp = 4;
friction_ = 0.1;
grounded = false;
vsp = 0;
dist = 250;
attack_dist = 50;
jumpdist = attack_dist/4;
attack_jump = 2;
damage = 10;
first_time = true;
knockout_timer_max = 60*2;
knockout_timer = knockout_timer_max;
stun_timer = 9;
stun_amount = 9;
xscale = 1;
yscale = 1;
